// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1Vs0Rc9G6Gp4zdXTGa3uATo_CS8v4NU',
    appId: '1:925014991534:web:a9966c9c5526060f6c033f',
    messagingSenderId: '925014991534',
    projectId: 'proj-82bcb',
    authDomain: 'proj-82bcb.firebaseapp.com',
    databaseURL: 'https://proj-82bcb-default-rtdb.firebaseio.com',
    storageBucket: 'proj-82bcb.appspot.com',
    measurementId: 'G-VMNY8MXFWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw1JISX8IYjuRN5OorwthZg5D5G9Fk1Ew',
    appId: '1:925014991534:android:ed3ff2b632aa4ab06c033f',
    messagingSenderId: '925014991534',
    projectId: 'proj-82bcb',
    databaseURL: 'https://proj-82bcb-default-rtdb.firebaseio.com',
    storageBucket: 'proj-82bcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkN9l3pm10P6BMv16RwvsixJ9yudL6Xo',
    appId: '1:925014991534:ios:dc4e39099ac4c6206c033f',
    messagingSenderId: '925014991534',
    projectId: 'proj-82bcb',
    databaseURL: 'https://proj-82bcb-default-rtdb.firebaseio.com',
    storageBucket: 'proj-82bcb.appspot.com',
    iosClientId: '925014991534-8j6h1gkfc75s7ic966ru3dtrg2v2gdeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkN9l3pm10P6BMv16RwvsixJ9yudL6Xo',
    appId: '1:925014991534:ios:dc4e39099ac4c6206c033f',
    messagingSenderId: '925014991534',
    projectId: 'proj-82bcb',
    databaseURL: 'https://proj-82bcb-default-rtdb.firebaseio.com',
    storageBucket: 'proj-82bcb.appspot.com',
    iosClientId: '925014991534-8j6h1gkfc75s7ic966ru3dtrg2v2gdeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
